component_types = {
    "naval_training": "Naval\nTraining",
    "large_taskforce_tactics": "Large\nTaskforce\nTactics",
    "general_equipment": "General\nEquipment",
    "aircraft_testing": "Aircraft\nTesting",
    "nuclear_physics": "Nuclear\nPhysics",
    "combined_arms_focus": "Combined Arms\nFocus",
    "mathematics": "Mathematics",
    "submarine_tactics": "Submarine\nTactics",
    "carrier_tactics": "Carrier\nTactics",
    "piloting": "Piloting",
    "naval_artillery": "Naval\nArtillery",
    "infantry_focus": "Infantry\nFocus",
    "technical_efficiency": "Technical\nEfficiency",
    "management": "Management",
    "large_unit_tactics": "Large Unit\nTactics",
    "decentralized_execution": "Decentralized\nExecution",
    "small_unit_tactics": "Small Unit\nTactics",
    "bomber_tactics": "Bomber\nTactics",
    "rocketry": "Rocketry",
    "seamanship": "Seamanship",
    "large_unit_focus": "Large Unit\nFocus",
    "fighter_tactics": "Fighter\nTactics",
    "artillery": "Artillery",
    "centralized_execution": "Centralized\nExecution",
    "individual_courage": "Individual\nCourage",
    "industrial_engineering": "Industrial\nEngineering",
    "chemistry": "Chemistry",
    "electronics": "Electronics",
    "aeronautics": "Aeronautics",
    "small_taskforce_tactics": "Small Taskforce\nTactics",
    "naval_engineering": "Naval\nEngineering",
    "mechanics": "Mechanics",
    "training": "Training",
    "nuclear_engineering": "Nuclear\nEngineering"
}