component_types = {
    "naval_training": "NAV_TRNG",
    "large_taskforce_tactics": "L_F_TACT",
    "general_equipment": "GEN_EQUI",
    "aircraft_testing": "AIR_TEST",
    "nuclear_physics": "NUC_PHYS",
    "combined_arms_focus": "COMB_RMS",
    "mathematics": "MATHEMAT",
    "submarine_tactics": "SUB_TACT",
    "carrier_tactics": "CAR_TACT",
    "piloting": "PILOTING",
    "naval_artillery": "NAV_ARTI",
    "infantry_focus": "INF_FOCU",
    "technical_efficiency": "TECH_EFF",
    "management": "MANAGMNT",
    "large_unit_tactics": "L_U_TACT",
    "decentralized_execution": "DEC_EXEC",
    "small_unit_tactics": "S_U_TACT",
    "bomber_tactics": "BOM_TACT",
    "rocketry": "ROCKETRY",
    "seamanship": "SEAMANSH",
    "large_unit_focus": "L_U_FOCU",
    "fighter_tactics": "FTR_TACT",
    "artillery": "ARTILLER",
    "centralized_execution": "CEN_EXEC",
    "individual_courage": "I_COURAG",
    "industrial_engineering": "IND_ENGI",
    "chemistry": "CHEMISTR",
    "electronics": "ELECTRNC",
    "aeronautics": "AERONAUT",
    "small_taskforce_tactics": "S_T_TACT",
    "naval_engineering": "NAV_ENGI",
    "mechanics": "MECHANCS",
    "training": "TRAINING",
    "nuclear_engineering": "NUC_ENGI"
}

# component names in file tech_names.csv
# key: f"RT_{component_type.upper()}"
